global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'oforha-ai'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'jupyter'
    static_configs:
      - targets: ['jupyter:8888']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  - job_name: 'ai-services'
    static_configs:
      - targets: ['ai-service:5001']
    metrics_path: '/metrics'

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 