groups:
  - name: resource_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on {{ $labels.instance }}
          description: CPU usage is above 70% for 5 minutes

      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Critical CPU usage on {{ $labels.instance }}
          description: CPU usage is above 85% for 5 minutes

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 75
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on {{ $labels.instance }}
          description: Memory usage is above 75% for 5 minutes

      - alert: CriticalMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Critical memory usage on {{ $labels.instance }}
          description: Memory usage is above 90% for 5 minutes

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High disk usage on {{ $labels.instance }}
          description: Disk usage is above 80% for 5 minutes

      - alert: HighResponseTime
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High response time on {{ $labels.instance }}
          description: Response time is above 500ms for 5 minutes

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate on {{ $labels.instance }}
          description: Error rate is above 1% for 5 minutes

      - alert: HighUserCount
        expr: active_users > 800
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High user count
          description: Active users are above 800 for 5 minutes

      - alert: CriticalUserCount
        expr: active_users > 1000
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Critical user count
          description: Active users are above 1000 for 5 minutes

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service {{ $labels.instance }} is down
          description: Service has been down for more than 1 minute

      - alert: DatabaseHighConnections
        expr: mongodb_connections > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High database connections
          description: Database connections are above 1000 for 5 minutes

      - alert: RedisHighMemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Redis memory usage
          description: Redis memory usage is above 80% for 5 minutes

      - alert: CDNHighErrorRate
        expr: rate(cdn_errors_total[5m]) / rate(cdn_requests_total[5m]) * 100 > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CDN error rate
          description: CDN error rate is above 1% for 5 minutes 